backend:
  name: github
  repo: enzzoperez/enzoublog

media_folder: static/assets
public_folder: assets

collections:
  - name: enzoublog
    label: EnzouBlog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
